spring.application.name=busbooking

#connection to cloud database
spring.datasource.url=jdbc:mysql://mysql-13a1b825-rdheebiga-9aa1.c.aivencloud.com:10096/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_xLT2o1NkOjwVNT0vmeT

#Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
